# Generated by Django 2.2.5 on 2021-09-01 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackUpConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(default='crm', max_length=60, verbose_name='私服名称')),
                ('user', models.CharField(default='root', max_length=20, verbose_name='用户')),
                ('addr', models.CharField(default='127.0.0.0:8000', max_length=60, verbose_name='私服地址')),
                ('salt', models.CharField(default='vcrting', max_length=60, verbose_name='盐')),
                ('card', models.CharField(default='vcrting', max_length=120, verbose_name='通行证')),
                ('file_path', models.CharField(default='/root/SMSTask', max_length=120, verbose_name='SCP 目标路径')),
                ('is_dir', models.BooleanField(default=True, verbose_name='目标是文件？')),
                ('work_status', models.BooleanField(default=True, verbose_name='启用状态？')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': 'BackUp Conf 配置',
                'verbose_name_plural': 'BackUp Conf 配置',
            },
        ),
        migrations.CreateModel(
            name='BackUpWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='工作時間')),
                ('success', models.BooleanField(default=True, verbose_name='备份成功？')),
                ('saveing_path', models.CharField(default='/root/SMSTask', max_length=120, verbose_name='文件的储存路径')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('conf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backup.BackUpConf', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': '工作记录',
                'verbose_name_plural': '工作记录',
            },
        ),
    ]
