# Generated by Django 2.2.5 on 2021-09-02 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(default='VcrTing', max_length=60, verbose_name='用户名称')),
                ('pwd', models.CharField(default='123456', max_length=90, verbose_name='用户密码')),
                ('bg', models.SmallIntegerField(choices=[(0, 'normal'), (1, 'r16'), (2, 'r18'), (3, 'r20'), (5, 'game')], default=1, null=True, verbose_name='消息类型')),
                ('salt', models.CharField(default='qiong', max_length=60, verbose_name='盐')),
                ('bad_account', models.BooleanField(default=True, verbose_name='取消资格？')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '蓝用户',
                'verbose_name_plural': '蓝用户',
            },
        ),
    ]
